dist: trusty
sudo: required
notifications:
  email: false
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost-all-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
  # Check versions of gcc and g++ 
  - gcc -v && g++ -v 
  - ls -l
  - npm install
  - npm test
