dist: trusty
sudo: required
notifications:
  email: false
language:
  - cpp
compiler:
  - gcc
addons:
  sonarcloud:
    oraganization: alexguldemond-github
    branches:
      - master
      - sonar
    token:
      secure: "zT3312J+rAquZ9BDxfaar7EyEiVrN0Ssq/2+dwiOP70I/O0rD4CLBbkBNQBHMttONS/5uRPdyvh6YiStZ2neGf5GqieyFsWmcBZhPojJCMb+nfJQrzwlmhbLNKYjYlqGOrKWC8HrkHDOlwMT9k1gzkUb/0R6W9TxHp5VcmoX6KUDAsxgT2u7uj0ynd7nsdZ6UivjRrKXC1jxX8VsveHDNjy+VWJSiqefLbYJV/Ilekn43QOKNodx7gti03+06ztZvcEe9rzTTxZUXK427hXjIYs6EGKPJovcjhU3Yl5lCoN6tz9mshTozAILjurNXIg5q+i0KTkTdbOLt5L3halcCwX14m/qAO0wF8r55PhUPnr2osVXyeJJ1OzP7IQSl5Or2lN+O74anQ5tb7Eppv/ahJxw9eSLRLW2dGZ1bkQYE706Z4C17CVuO4g9hLtRs9LgQypBFsnHrMOnuqjmUjYmou598V+rtnPEOQvh4aGoQKMPZ6tNBpG9fpNvFmQV+nIlnXf2TwvoaGWGIzUFw+BUmrOxsnOTZ186U15/HaoETnXsHXtULr6niAkyaTzb8rxxAOddF+8K4uVbHwlBj1QN1CI/c/Jl/hn6KZoyk9TMNrwbWuUJmaMyjMB/Zyjiqaf60JxHRvE7LAsm6KkoFLsjJ6newciVVK1YGREUaL0UFAE="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost-all-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
  # Check versions of gcc and g++ 
  - gcc -v && g++ -v 
  - ls -l
  - sonar-scanner
  - npm install
  - npm test
